import { MigrationInterface, QueryRunner } from 'typeorm';

export class Phase3QuotesAppetiteMessaging1723376000000 implements MigrationInterface {
  name = 'Phase3QuotesAppetiteMessaging1723376000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // --- quotes: a type axis alongside the existing status lifecycle ---
    await queryRunner.query(`
      ALTER TABLE "quotes"
      ADD COLUMN IF NOT EXISTS "quoteType" varchar NOT NULL DEFAULT 'indication',
      ADD COLUMN IF NOT EXISTS "declineReason" text
    `);
    await queryRunner.query(`
      ALTER TABLE "quotes"
      ADD CONSTRAINT "CHK_quotes_quoteType"
      CHECK ("quoteType" IN ('indication', 'firm_order', 'binding'))
    `);

    // --- submission_history: allow the two quote events ---
    // The original CHECK was declared inline, so its name was generated by
    // Postgres. Find it by definition rather than guessing.
    await queryRunner.query(`
      DO $$
      DECLARE c record;
      BEGIN
        FOR c IN
          SELECT conname FROM pg_constraint
          WHERE conrelid = 'submission_history'::regclass
            AND contype = 'c'
            AND pg_get_constraintdef(oid) LIKE '%changeType%'
        LOOP
          EXECUTE format('ALTER TABLE "submission_history" DROP CONSTRAINT %I', c.conname);
        END LOOP;
      END $$
    `);
    await queryRunner.query(`
      ALTER TABLE "submission_history"
      ADD CONSTRAINT "CHK_submission_history_changeType"
      CHECK ("changeType" IN (
        'created', 'updated', 'status_changed', 'document_added',
        'document_removed', 'submitted', 'quote_received', 'quote_status_changed'
      ))
    `);

    // --- notifications ---
    await queryRunner.query(`
      CREATE TABLE "notifications" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "userId" uuid NOT NULL,
        "type" varchar NOT NULL CHECK ("type" IN (
          'quote_received', 'quote_status_changed', 'message_received',
          'submission_status_changed'
        )),
        "title" varchar NOT NULL,
        "body" text,
        "data" json,
        "isRead" boolean NOT NULL DEFAULT false,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "FK_notifications_user" FOREIGN KEY ("userId")
          REFERENCES "users"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_notifications_user_unread" ON "notifications" ("userId", "isRead")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_notifications_createdAt" ON "notifications" ("createdAt")`,
    );

    // --- risk_appetites ---
    await queryRunner.query(`
      CREATE TABLE "risk_appetites" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "name" varchar NOT NULL,
        "reinsurerId" uuid NOT NULL,
        "linesOfBusiness" json NOT NULL,
        "submissionTypes" json,
        "countries" json,
        "worldwide" boolean NOT NULL DEFAULT false,
        "structurePreference" varchar NOT NULL DEFAULT 'any'
          CHECK ("structurePreference" IN ('proportional', 'non_proportional', 'any')),
        "minSumInsured" decimal(15,2),
        "maxSumInsured" decimal(15,2),
        "currency" varchar,
        "maxCapacityShare" decimal(10,2),
        "notes" text,
        "isActive" boolean NOT NULL DEFAULT true,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "FK_risk_appetites_reinsurer" FOREIGN KEY ("reinsurerId")
          REFERENCES "organizations"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_risk_appetites_reinsurer_active" ON "risk_appetites" ("reinsurerId", "isActive")`,
    );

    // --- message_threads: one per submission per counterparty ---
    await queryRunner.query(`
      CREATE TABLE "message_threads" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "submissionId" uuid NOT NULL,
        "cedantOrgId" uuid NOT NULL,
        "counterpartyOrgId" uuid NOT NULL,
        "subject" varchar,
        "lastMessageAt" timestamp,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "FK_threads_submission" FOREIGN KEY ("submissionId")
          REFERENCES "submissions"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_threads_cedant_org" FOREIGN KEY ("cedantOrgId")
          REFERENCES "organizations"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_threads_counterparty_org" FOREIGN KEY ("counterpartyOrgId")
          REFERENCES "organizations"("id") ON DELETE CASCADE,
        CONSTRAINT "UQ_thread_per_counterparty"
          UNIQUE ("submissionId", "cedantOrgId", "counterpartyOrgId")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_threads_submission" ON "message_threads" ("submissionId")`,
    );

    // --- messages ---
    await queryRunner.query(`
      CREATE TABLE "messages" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "threadId" uuid NOT NULL,
        "senderId" uuid NOT NULL,
        "senderOrgId" uuid NOT NULL,
        "body" text NOT NULL,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "FK_messages_thread" FOREIGN KEY ("threadId")
          REFERENCES "message_threads"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_messages_sender" FOREIGN KEY ("senderId")
          REFERENCES "users"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_messages_sender_org" FOREIGN KEY ("senderOrgId")
          REFERENCES "organizations"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_messages_thread_created" ON "messages" ("threadId", "createdAt")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "messages"`);
    await queryRunner.query(`DROP TABLE "message_threads"`);
    await queryRunner.query(`DROP TABLE "risk_appetites"`);
    await queryRunner.query(`DROP TABLE "notifications"`);

    await queryRunner.query(
      `ALTER TABLE "submission_history" DROP CONSTRAINT IF EXISTS "CHK_submission_history_changeType"`,
    );
    await queryRunner.query(`
      ALTER TABLE "submission_history"
      ADD CONSTRAINT "CHK_submission_history_changeType"
      CHECK ("changeType" IN (
        'created', 'updated', 'status_changed', 'document_added',
        'document_removed', 'submitted'
      ))
    `);

    await queryRunner.query(
      `ALTER TABLE "quotes" DROP CONSTRAINT IF EXISTS "CHK_quotes_quoteType"`,
    );
    await queryRunner.query(
      `ALTER TABLE "quotes" DROP COLUMN IF EXISTS "declineReason", DROP COLUMN IF EXISTS "quoteType"`,
    );
  }
}
